### ISSUE TITLE
Logs routing tenant is not getting created and giving error on paasing enable_platform_logs as true

### ISSUE THREAD

**Issue by nupurg-ibm** [terraform-ibm-modules/terraform-ibm-observability-instances#605]
When setting true for enable_platform_logs, I am seeing below issue:
I am not specifying any region separately as I want to create the tenant in the same region where we have cloud logs instance.
I have checked there is no existing tenant present in that region, still got this conflict error.

```
│ Error: ---
│ id: terraform-99c5b7b1
│ summary: 'CreateTenantWithContext failed: Conflict'
│ severity: error
│ resource: ibm_logs_router_tenant
│ operation: create
│ component:
│   name: [github.com/IBM-Cloud/terraform-provider-ibm](http://github.com/IBM-Cloud/terraform-provider-ibm)
│   version: 1.71.0
│ ---
│
│
│   with module.cloud_monitoring_instance_creation.module.observability_instance.module.cloud_logs[0].ibm_logs_router_tenant.logs_router_tenant_instances["us-east"],
│   on .terraform/modules/cloud_monitoring_instance_creation.observability_instance/modules/cloud_logs/main.tf line 166, in resource "ibm_logs_router_tenant" "logs_router_tenant_instances":
│  166: resource "ibm_logs_router_tenant" "logs_router_tenant_instances" {

```

**Comment by ocofaigh** [comment]
@nupurg-ibm I saw this during development once, and it turned out we had some tenants already in some regions that did not show in the UI, but did show using the api. Perhaps try list all tenants using the api in your account.
`curl -X GET https://management/.${REGION}.logs-router.cloud.ibm.com/v1/tenants -H "Authorization: ${token}" -H "IBM-API-Version: 2024-03-01"`

**Comment by nupurg-ibm** [comment]
I saw the tenant via API and now I am able to create the tenant. Hence closing the issue.
